name: CICD Pipeline

on: 
  push:

jobs:
  code:
    uses: ./.github/workflows/code.yaml
  build:
    needs: code
    uses: ./.github/workflows/build.yaml
  test:
    needs:  code
    uses: ./.github/workflows/test.yaml
  push:
    needs: build
    uses: ./.github/workflows/push.yaml
