name: deploy
on: 
  push: 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: code clone
        uses:  actions/checkout@v7
      - name: deploy code
        run: cp index.html /usr/share/nginx/html
        
